# Generated by Django 4.2.3 on 2023-07-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
